In [1]:
import torch

In [2]:
# Создаем входной массив из двух изображений RGB 3*3
input_images = torch.tensor(
      [[[[0,  1,  2],
         [3,  4,  5],
         [6,  7,  8]],

        [[9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])


def get_padding2d(input_images):
    #padded_images = # добавить нулей с четырех сторон каждого изображения
    ## Top button
    t=list(input_images.size())
    t[2]=1
    newrow=torch.zeros(t)
    newrow=newrow.type(torch.long)
    input_images=input_images.type(torch.long)
    
    input_images=torch.cat((newrow, input_images), 2)
    input_images=torch.cat((input_images,newrow), 2)
    input_images


    ## Sides
    t=list(input_images.size())
    t[-1]=1
    newrow=torch.zeros(t)
    newrow=newrow.type(torch.long)
    input_images=input_images.type(torch.long)
    
    input_images=torch.cat((newrow, input_images), 3)
    input_images=torch.cat((input_images, newrow), 3)
    padded_images=input_images
    
    padded_images=padded_images.type(torch.float)
    return padded_images

In [3]:
get_padding2d(input_images)

tensor([[[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  1.,  2.,  0.],
          [ 0.,  3.,  4.,  5.,  0.],
          [ 0.,  6.,  7.,  8.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  9., 10., 11.,  0.],
          [ 0., 12., 13., 14.,  0.],
          [ 0., 15., 16., 17.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0., 18., 19., 20.,  0.],
          [ 0., 21., 22., 23.,  0.],
          [ 0., 24., 25., 26.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0., 27., 28., 29.,  0.],
          [ 0., 30., 31., 32.,  0.],
          [ 0., 33., 34., 35.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0., 36., 37., 38.,  0.],
          [ 0., 39., 40., 41.,  0.],
          [ 0., 42., 43., 44.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0., 45., 46., 

## My Conv2d

In [6]:
import torch
from abc import ABC, abstractmethod


def calc_out_shape(input_matrix_shape, out_channels, kernel_size, stride, padding):
    batch_size, channels_count, input_height, input_width = input_matrix_shape
    output_height = (input_height + 2 * padding - (kernel_size - 1) - 1) // stride + 1
    output_width = (input_width + 2 * padding - (kernel_size - 1) - 1) // stride + 1

    return batch_size, out_channels, output_height, output_width


class ABCConv2d(ABC):
    def __init__(self, in_channels, out_channels, kernel_size, stride):
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride

    def set_kernel(self, kernel):
        self.kernel = kernel

    @abstractmethod
    def __call__(self, input_tensor):
        pass


In [64]:
kernel = torch.tensor(
                  [[[[0., 1, 0],
                     [1,  2, 1],
                     [0,  1, 0]],

                    [[1, 2, 1],
                     [0, 3, 3],
                     [0, 1, 10]],

                    [[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]]]])

In [62]:
# Сверточный слой через циклы.
class Conv2dLoop(ABCConv2d):

    def calc_out_shape(input_matrix_shape, out_channels, kernel_size, stride, padding):
        batch_size, channels_count, input_height, input_width = input_matrix_shape
        output_height = (input_height + 2 * padding - (kernel_size - 1) - 1) // stride + 1
        output_width = (input_width + 2 * padding - (kernel_size - 1) - 1) // stride + 1
    
        return batch_size, out_channels, output_height, output_width

    def out_image_shape(self, input_height, input_width, kernel_size, stride, padding):
        output_height = (input_height + 2 * padding - (kernel_size - 1) - 1) // stride + 1
        output_width = (input_width + 2 * padding - (kernel_size - 1) - 1) // stride + 1
        return output_height, output_width

    def create_empty_out_img(self, input_tensor):
        self.input_width = input_tensor.shape[-1]
        self.input_height = input_tensor.shape[-2]
        # in_chanels = input_tensor.shape[-3]
        
        padding = 0
        output_height,output_width= self.out_image_shape(input_height,input_width, self.kernel_size, self.stride, padding)
        
        out_tesor = torch.zeros([self.in_channels, output_height, output_width])
        return out_tesor

    def conv_one_sample(self):

        for h in range(self.input_height):
            for w in range(self.input_width):
            
        
        
    def __call__(self, input_tensor):
        # output_tensor = # Напишите в этом месте вычисление свертки с использованием циклов.

        # create
        self.out_tensor=self.create_empty_out_img(input_tensor)
        self.conv_one_sample(input_tensor)

        return out_tesor
        # # проверка является ли input батчем ( dimension = 4 => batch, dimension = 3 => one_image)
        # if len(input_tensor.shape) = 4:
        #     for i in input_tensor.shape[0]:
        # return output_tensor


In [65]:
in_channels = 3
out_channels = 4
kernel_size = 3
stride = 1


my_conv = Conv2dLoop(in_channels, out_channels, kernel_size, stride)
my_conv.set_kernel(kernel)

img = torch.randint(10, ( 3, 7, 10)).to(torch.float32)
my_conv(img)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [66]:
img

tensor([[[3., 8., 1., 4., 6., 1., 0., 6., 0., 7.],
         [2., 0., 1., 4., 2., 5., 2., 9., 6., 6.],
         [8., 4., 8., 6., 0., 1., 9., 5., 7., 5.],
         [9., 3., 5., 2., 2., 1., 8., 0., 1., 6.],
         [9., 7., 8., 7., 8., 4., 2., 1., 0., 6.],
         [9., 5., 4., 5., 9., 7., 1., 3., 1., 2.],
         [6., 5., 6., 0., 9., 1., 5., 2., 1., 9.]],

        [[6., 2., 9., 3., 6., 8., 5., 3., 5., 3.],
         [5., 9., 4., 3., 4., 9., 7., 0., 6., 0.],
         [5., 0., 2., 4., 3., 9., 7., 9., 8., 2.],
         [5., 1., 0., 1., 6., 2., 7., 4., 9., 9.],
         [9., 4., 9., 0., 9., 7., 5., 3., 3., 7.],
         [4., 8., 3., 9., 2., 7., 1., 3., 4., 1.],
         [3., 3., 1., 0., 4., 2., 2., 1., 2., 8.]],

        [[0., 9., 5., 7., 8., 8., 7., 6., 8., 8.],
         [3., 6., 2., 1., 2., 2., 5., 6., 4., 4.],
         [7., 2., 9., 9., 4., 1., 5., 6., 1., 2.],
         [9., 3., 6., 5., 9., 8., 9., 7., 9., 0.],
         [4., 5., 1., 0., 9., 2., 6., 1., 3., 0.],
         [7., 7., 9., 4., 8

In [67]:
img[:,0:3,0:3]

tensor([[[3., 8., 1.],
         [2., 0., 1.],
         [8., 4., 8.]],

        [[6., 2., 9.],
         [5., 9., 4.],
         [5., 0., 2.]],

        [[0., 9., 5.],
         [3., 6., 2.],
         [7., 2., 9.]]])

In [48]:
a = torch.randint(10, ( 3, 7, 10)).to(torch.float32)
input_width=a.shape[-1]
input_height=a.shape[-2]
kernel_size =5
stride = 1
padding=0


def image_shape(input_height, input_width, kernel_size, stride, padding):
    output_height = (input_height + 2 * padding - (kernel_size - 1) - 1) // stride + 1
    output_width = (input_width + 2 * padding - (kernel_size - 1) - 1) // stride + 1
    return output_height, output_width

output_height,output_width=image_shape(input_height, input_width,kernel_size,stride, padding)

print(output_height,output_width)

3 6


In [ ]:
kernel = torch.tensor(
                  [[[[0., 1, 0],
                     [1,  2, 1],
                     [0,  1, 0]],

                    [[1, 2, 1],
                     [0, 3, 3],
                     [0, 1, 10]],

                    [[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]]]])

out_channels = kernel.shape[0]
in_channels  = kernel.shape[1]
kernel_size  = kernel.shape[2]
stride=2

print(f" \
out_channels {out_channels} \n \
in_channels  {in_channels}  \n \
kernel_size  {kernel_size}  \n \
"
)

In [ ]:
my_conv2d = Conv2dLoop(in_channels, out_channels, kernel_size, stride)
my_conv2d.set_kernel(kernel)

In [ ]:
input_tensor.shape[0]

In [ ]:
len(input_tensor.shape)

In [ ]:
## Torch conv2d

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])

In [27]:
a = torch.randint(10, (2, 3, 7, 7)).to(torch.float32)
a.shape[0]
# for i in a:
#     print(i.shape)

2

In [45]:
class Conv2d(ABCConv2d):
    def __init__(self, in_channels, out_channels, kernel_size, stride):
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size,
                                      stride, padding=0, bias=False)

    def set_kernel(self, kernel):
        self.conv2d.weight.data = kernel

    def __call__(self, input_tensor):
        return self.conv2d(input_tensor)

In [46]:
torch_conv2d = Conv2d(3,4,5,1)
torch_conv2d(a).shape
torch_conv2d(a).shape

torch.Size([4, 3, 6])

In [29]:
a[0].shape

torch.Size([3, 7, 7])

In [30]:
def calc_out_shape(input_matrix_shape, out_channels, kernel_size, stride, padding):
    batch_size, channels_count, input_height, input_width = input_matrix_shape
    output_height = (input_height + 2 * padding - (kernel_size - 1) - 1) // stride + 1
    output_width = (input_width + 2 * padding - (kernel_size - 1) - 1) // stride + 1

    return batch_size, out_channels, output_height, output_width

calc_out_shape(a.shape, 4, 5, 1, 0)

(2, 4, 3, 3)

In [ ]:
## Test input 

In [53]:
kernel = torch.tensor(
                  [[[[0., 1, 0],
                     [1,  2, 1],
                     [0,  1, 0]],

                    [[1, 2, 1],
                     [0, 3, 3],
                     [0, 1, 10]],

                    [[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]]]])

in_channels = kernel.shape[1]
in_channels

3

In [57]:
batch_size=2
input_height=4
input_width=4
stride=2


print(batch_size * in_channels * \
                            input_height * input_width)

input_tensor = torch.arange(0, batch_size * in_channels *
                            input_height * input_width,
                            out=torch.FloatTensor()) \
    .reshape(batch_size, in_channels, input_height, input_width)
print(input_tensor.shape)
input_tensor.shape[-3]

96
torch.Size([2, 3, 4, 4])


3